export const REGISTRATION_BEGINS = 'REGISTRATION_BEGINS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const POSTAD_BEGINS = 'POSTAD_BEGINS';
export const POSTAD_SUCCESS = 'POSTAD_SUCCESS';
export const POSTAD_ERROR = 'POSTAD_ERROR';

export const FIND_BY_CATEGORY_BEGINS = 'FIND_BY_CATEGORY_BEGINS';
export const FIND_BY_CATEGORY_SUCCESS = 'FIND_BY_CATEGORY_SUCCESS';
export const FIND_BY_CATEGORY_ERROR = 'FIND_BY_CATEGORY_ERROR';

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_SCHOOL = 'SET_ACTIVE_SCHOOL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_SECOND_USER_ID = 'SET_SECOND_USER_ID';


export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';

export const HIDE_CHAT_BOX = 'HIDE_CHAT_BOX';

export const OPEN_FILTER_MODAL = 'OPEN_FILTER_MODAL';

export const DROPDOWN_TOGGLE = 'DROPDOWN_TOGGLE';



// export const  = 'SET_CURRENT_USER';
